# Generated by Django 4.1.2 on 2024-03-01 19:29

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_product_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productimages",
            old_name="images",
            new_name="image",
        ),
        migrations.AddField(
            model_name="product",
            name="imageThumb",
            field=models.ImageField(
                default="productThumb.jpg", upload_to=core.models.user_directory_path
            ),
        ),
        migrations.AddField(
            model_name="productimages",
            name="thumbnail",
            field=models.ImageField(
                default="product_thumb.jpg", upload_to="product-thumbnails"
            ),
        ),
    ]
