# Generated by Django 4.1.2 on 2024-03-07 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_productattribute_productvariation"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductAttributeOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("option", models.CharField(max_length=100)),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="core.productattribute",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Attribute Option",
                "verbose_name_plural": "Product Attribute Options",
            },
        ),
    ]
