# Generated by Django 4.1.2 on 2024-03-07 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_productattributeoption"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariation",
            name="value",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.productattributeoption",
                verbose_name="Attribute Value",
            ),
        ),
    ]
